// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt9jzwj17CEbJ-_nG8IQPC6ky2xoP7ZBc',
    appId: '1:90530775203:web:5494729ade47d3b21bbf16',
    messagingSenderId: '90530775203',
    projectId: 'divvy-3555d',
    authDomain: 'divvy-3555d.firebaseapp.com',
    storageBucket: 'divvy-3555d.firebasestorage.app',
    measurementId: 'G-1QSLD2ZK0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzaD7rAf-SDjCWMiqFEGmW8tURI8t8VCg',
    appId: '1:90530775203:android:bdc86994581a04591bbf16',
    messagingSenderId: '90530775203',
    projectId: 'divvy-3555d',
    storageBucket: 'divvy-3555d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4N8lNForh0SwzGcvJ7tQYun_glHlq3-g',
    appId: '1:90530775203:ios:d42a08e30dd426511bbf16',
    messagingSenderId: '90530775203',
    projectId: 'divvy-3555d',
    storageBucket: 'divvy-3555d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4N8lNForh0SwzGcvJ7tQYun_glHlq3-g',
    appId: '1:90530775203:ios:d42a08e30dd426511bbf16',
    messagingSenderId: '90530775203',
    projectId: 'divvy-3555d',
    storageBucket: 'divvy-3555d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt9jzwj17CEbJ-_nG8IQPC6ky2xoP7ZBc',
    appId: '1:90530775203:web:379912a570100bee1bbf16',
    messagingSenderId: '90530775203',
    projectId: 'divvy-3555d',
    authDomain: 'divvy-3555d.firebaseapp.com',
    storageBucket: 'divvy-3555d.firebasestorage.app',
    measurementId: 'G-4CFEQ9SE1D',
  );

}